### ISSUE TITLE
Don't run on default port 3030 in production

### ISSUE THREAD

**Issue by roopakv** [SouthbankSoftware/dbkoda#10]
A lot of developers who will use this app probably use 3030 for their apps, and it took me a while to figure out that running my app in the background broke dbKoda, in production it might be worth looking into using a random high port, or give the user to change this somehow :)

**Comment by michaeljharrison** [comment]
Hey there,

Thanks for giving dbKoda a try and letting us know of this issue, you're absolutely right!
We'll make a change so that dbKoda finds an unused port on start up so it doesn't interfere with your other apps. We'll put this in our next hotfix release and I'll update this issue once it's available. :)

Kind Regards,
Mike from dbKoda.

**Comment by roopakv** [comment]
Thank you for the quick response! We're just starting to use it, finding it to be super useful :)

**Comment by michaeljharrison** [comment]
Hey,

Just letting you know the new version of dbKoda is out today and the fix for this issue is in there, you can grab the latest version on [dbkoda.com](dbkoda.com) along with the full release notes for 0.10. Thanks again for helping us improve the product!

Thanks,
Mike from dbKoda.

**Comment by roopakv** [comment]
Thank you for following up @michaeljharrison ! will check out the new version as soon as .i get a chance
