### ISSUE TITLE
Connect through SSH with another port

### ISSUE THREAD

**Issue by alexdeoliveira** [SouthbankSoftware/dbkoda#11]
Hello, I need to connect via SSH through port 10900. How do I do?

**Comment by gharriso** [comment]
High Alex,  we had the SSH port hardcoded at 22 unfortunately.  I put a talk into this weeks sprint to make it a configuration variable - that should show up in the nightly builds by the end of the week - I'll keep you posted.

**Comment by smartynov** [comment]
@alexdeoliveira as a temporary measure you can set up ssh port 22 forwarding from local host to remote via `ssh` on Mac OS and Linux or putty or some other ssh client on Windows.

**Comment by michaeljharrison** [comment]
Hi,

Just letting you know the new version of dbKoda is out and the fix for this issue is in there, SSH port can now be configured in the connection wizard. You can grab the latest version on dbkoda.com along with the full release notes for 0.10. Thanks again for helping us improve the product!

Kind Regards,
Mike from dbKoda.
