### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by lorensr** [SouthbankSoftware/dbkoda#18]
This URI works in mongochef, but I'm getting Authentication error in dbKoda. Of the form:

`mongodb://username:password@domain.mlab.com:port/dbname`

![image](https://user-images.githubusercontent.com/251288/41504082-3cfac27a-71b2-11e8-939a-83f0e469a1b6.png)

(w/ user/pass replaced w/ actual values)

**Comment by lorensr** [comment]
![image](https://user-images.githubusercontent.com/251288/41504086-57ff5f40-71b2-11e8-9489-f3d64383c8cb.png)

**Comment by wshamim** [comment]
Hi Loren,

Sorry for the late response, 

After looking into your bug, I figured out the issue which is appearing because of not parsing the URL for all other params like database, etc.

We are working on a fix for this and will make all the fields update bidirectionally. 

Meanwhile, you can try and update the **database** name in the **database field** and it should connect fine.

Hope this helps.

Wahaj from dbKoda
