### ISSUE TITLE
Failed to create Mongo shell, which exited with code 1 and output message at MongoShell.

### ISSUE THREAD

**Issue by Echo009** [SouthbankSoftware/dbkoda#64]
#### Environment
Operating system :  osx (version 10.15.3)
dbkoda version : v1.1.0

#### config.yml
**use Docker and do not create new container** 
![image](https://user-images.githubusercontent.com/24402043/80361186-1ae59b00-88b3-11ea-928d-c7d5a7bb1300.png)

#### Error Information

![image](https://user-images.githubusercontent.com/24402043/80361796-1a013900-88b4-11ea-802b-6e7b34edc5b9.png)

**it is no problem from the command** 
![image](https://user-images.githubusercontent.com/24402043/80362766-ca237180-88b5-11ea-85a4-06d117246ed7.png)

**I need you help , thank you very much.** (･ェ･。)

**Comment by Echo009** [comment]
@guiguan  I need you help , thank you very much. (･ェ･。)

**Comment by guiguan** [comment]
@Echo009 I think your configuration is correct. The problem is that you were trying to connect to the mongo server in the same container as the mongo client. `dbKoda` makes use of both `mongo` binary (shell) and mongo driver connections. In your case, the `mongo` binary can connect to the server correctly, as they both are in the same local container network. However, the mongo driver cannot connect, because it is on your host level.

If you try to connect to an external mongo server, your config should work. If you still want to connect to the mongo server in your docker container, you can expose the server port (27017) to your host, then use your host_ip:27017 (not `localhost`) as the host port in the mongo connection string.

**Comment by Echo009** [comment]
> @Echo009 I think your configuration is correct. The problem is that you were trying to connect to the mongo server in the same container as the mongo client. `dbKoda` makes use of both `mongo` binary (shell) and mongo driver connections. In your case, the `mongo` binary can connect to the server correctly, as they both are in the same local container network. However, the mongo driver cannot connect, because it is on your host level.
> 
> If you try to connect to an external mongo server, your config should work. If you still want to connect to the mongo server in your docker container, you can expose the server port (27017) to your host, then use your host_ip:27017 (not `localhost`) as the host port in the mongo connection string.


Thank you very much .

**Comment by echotrue** [comment]
If you want to connect to the mongo server in your docker container.
